<?php
namespace Veles\Tests\ErrorHandler;

use Veles\ErrorHandler\ExceptionHandler;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-11 at 19:46:34.
 * @group ErrorHandler
 */
class ExceptionHandlerTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var ExceptionHandler
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new ExceptionHandler;
	}

	/**
	 * @covers       Veles\ErrorHandler\ExceptionHandler::run
	 * @dataProvider runProvider
	 *
	 * @param $e
	 * @param $time
	 * @param $expected
	 */
	public function testRun($e, $time, $expected)
	{
		$this->object->setTime($time);
		$this->object->run($e);

		$result = $this->object->getVars();

		$msg = 'ExceptionHandler::run() wrong behavior!';
		$this->assertSame($expected, $result, $msg);
	}

	public function runProvider()
	{
		$msg = 'runProvider Exception';
		try {
			throw new \Exception($msg);
		} catch(\Exception $e) {}

		$time = strftime('%Y-%m-%d %H:%M:%S', time());

		$expected = [
			'time'    => $time,
			'message' => $msg,
			'file'    => realpath(__FILE__),
			'line'    => 49,
			'stack'   => array_reverse($e->getTrace()),
			'type'    => 0,
			'defined' => ['exception' => $e]
		];

		return [
			[$e, $time, $expected]
		];
	}
}
